spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: gandy867
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

      #spring.application.name=security
      #spring.datasource.url = jdbc:postgresql://localhost:5432/jwt_security
      #spring.datasource.username = jwt_security
      #spring.datasource.password = gandy867
      #spring.datasource.driver-class-name=org.postgresql.Driver
      #
      ## Hibernate properties
      #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      #spring.jpa.hibernate.ddl-auto=create-drop

      #spring:
      #  datasource:
      #    url: jdbc:postgresql://localhost:5432/jwt_security
      #    username: postgres
      #    password: gandy867
      #    driver-class-name: org.postgresql.Driver
      #  jpa:
      #    hibernate:
      #      ddl-auto: create-drop
      #    show-sql: true
      #    properties:
      #      hibernate:
      #        dialect: org.hibernate.dialect.PostgreSQLDialect
      #        format-sql: true
      #      database: postgresql
      #      database-platform: org.hibernate.dialect.PostgreSQLDialect